### ISSUE TITLE
Error on lambda functions

### ISSUE THREAD

**Issue by gls7** [jcberquist/commandbox-cfformat#100]
With this code:
`arguments.prc.teacherSessions = prc.eligibility.sessions
	.filter(session => session.type == "fsy_teacher")
	.map(session => LSParseNumber(session.id));
`

I get this error:
`key [DELIMITED_ELEMENTS] doesn't exist
\modules\commandbox-cfformat\models\Delimited.cfc: line 11`

When I change it to this it works fine:
`arguments.prc.teacherSessions = prc.eligibility.sessions
	.filter((session) => session.type == "fsy_teacher")
	.map((session) => LSParseNumber(session.id));
`

Perhaps not using parens for the params is an "undocumented feature" in CF, but it's accepted and works.

**Comment by jcberquist** [comment]
Yes, Thanks for reporting this, it is definitely an issue with the single bare parameter.

**Comment by jcberquist** [comment]
This should be fixed in `v0.15.16` - thanks again!
