### ISSUE TITLE
Error processing custom tags

### ISSUE THREAD

**Issue by gls7** [jcberquist/commandbox-cfformat#101]
I'm seeing errors with processing custom tags.

`Array index [2] out of range, array size is [1]`

C:\Users\xxx\.CommandBox\cfml\modules\commandbox-cfformat\models\CFFormat.cfc: line 274
272:                 var idx = 1;
273:                 while (token.elements[idx++][2].find('entity.name.tag.custom.cfml')) {
274:                     **tagName &= token.elements[idx][1];**
275:                 }
276:             }

I found this unit test in your code which made me think that you're looking for something like this:
`<pbn:link-returnto href="xxx" text="xxx"/>`

But our custom tags don't have a prefix. Here's an example:
`<cf_mail to="#toEmail#" from="#from#" subject="Data Validation Report">
     ...
</cf_mail>
`

**Comment by jcberquist** [comment]
This should also be fixed in `v0.15.16`. Thanks.

**Comment by gls7** [comment]
> This should also be fixed in `v0.15.16`. Thanks.

How/when is that made available to commandbox? Assuming I can `update cfformat` in commandbox. Or is there a better way to keep up to date?

**Comment by jcberquist** [comment]
I publish releases to ForgeBox as they are produced on GitHub. So it should be available for update now.
