### ISSUE TITLE
Suggestion: Add more context for "Unbalanced closing tag found" errors

### ISSUE THREAD

**Issue by gls7** [jcberquist/commandbox-cfformat#102]
We have a cfc that builds emails based on many conditions. We create both text and html versions of the messages. In this situation we may have starting and ending tags in different code blocks so we'll need to ignore those parts. The problem is finding them as the current error message doesn't give line numbers or larger context of the line or other information to find the problem.

**Comment by jcberquist** [comment]
Unfortunately, given the way the formatting currently works, accessing the line numbers for these errors is tricky. I built a separate command into cfformat to try and help with these situations. Could you try using the command `cfformat tag-check` on the files causing the errors?

**Comment by gls7** [comment]
That's perfect! I got through the mess of tags and it's all good now. Thanks!

**Comment by gls7** [comment]
That's perfect! I got through the mess of tags and it's all good now. Thanks!
