### ISSUE TITLE
Too much spacing

### ISSUE THREAD

**Issue by gls7** [jcberquist/commandbox-cfformat#104]
With "binary_operators.padding": true each successive time the file is formatted it adds more space.
```
a = b
a  = b
a   = b
```
Noticing the above on concatenation & as well.

Also seeing strangeness with adding too many tabs.
`TAB TAB TAB TAB local.bed1=local.rooms[local.selectedRoom].beds[local.rooms[local.selectedRoom].beds.find(local.bedFinder(unhousedMember.wheelchair, unhousedMember.no_stairs))]`

becomes
`TAB TAB TAB TAB TAB TAB TAB TAB local.bed1=local.rooms[local.selectedRoom].beds[
TAB TAB TAB TAB TAB local.rooms[local.selectedRoom].beds.find(local.bedFinder(unhousedMember.wheelchair, unhousedMember.no_stairs))
TAB TAB TAB TAB]`

**Comment by gls7** [comment]
Just noticed this as well:
if (!local.info.keyExists("spouse")) local.info.spouse = 0 // API may send nulls which throw reference errors in CF
if (!local.info.keyExists("type")) local.info.type = "" // API may send nulls which throw reference errors in CF
if (!local.info.keyExists("rank")) local.info.rank = "" // API may send nulls which throw reference errors in CF
if (!local.info.keyExists("approved")) local.info.approved = false // API may send nulls which throw reference errors in CF
if (!local.info.keyExists("sessions")) local.info.sessions = [] // API may send nulls which throw reference errors in CF

becomes

if (!local.info.keyExists("spouse"))
TAB local.info.spouse = 0 // API may send nulls which throw reference errors in CF
TAB if (!local.info.keyExists("type"))
TAB TAB local.info.type = "" // API may send nulls which throw reference errors in CF
TAB TAB if (!local.info.keyExists("rank"))
TAB TAB TAB local.info.rank = "" // API may send nulls which throw reference errors in CF
TAB TAB TAB if (!local.info.keyExists("approved"))
TAB TAB TAB TAB local.info.approved = false // API may send nulls which throw reference errors in CF
TAB TAB TAB TAB if (!local.info.keyExists("sessions"))
TAB TAB TAB TAB TAB local.info.sessions = [] // API may send nulls which throw reference errors in CF

Seems that when the curly braces are not used after an IF it goes to lunch.

**Comment by gls7** [comment]
{
	"alignment.consecutive.assignments": false,
	"alignment.consecutive.params": false,
	"alignment.consecutive.properties": false,
	"array.empty_padding": false,
	"array.multiline.comma_dangle": false,
	"array.multiline.element_count": 4,
	"array.multiline.leading_comma": false,
	"array.multiline.leading_comma.padding": true,
	"array.multiline.min_length": 120,
	"array.padding": false,
	"binary_operators.padding": true,
	"brackets.padding": false,
	"comment.asterisks": "align",
	"for_loop_semicolons.padding": true,
	"function_anonymous.empty_padding": false,
	"function_anonymous.group_to_block_spacing": "spaced",
	"function_anonymous.multiline.comma_dangle": false,
	"function_anonymous.multiline.element_count": 4,
	"function_anonymous.multiline.leading_comma": false,
	"function_anonymous.multiline.leading_comma.padding": true,
	"function_anonymous.multiline.min_length": 120,
	"function_anonymous.padding": false,
	"function_anonymous.spacing_to_group": false,
	"function_call.casing.builtin": "pascal",
	"function_call.casing.userdefined": "camel",
	"function_call.empty_padding": false,
	"function_call.multiline.comma_dangle": false,
	"function_call.multiline.element_count": 4,
	"function_call.multiline.leading_comma": false,
	"function_call.multiline.leading_comma.padding": true,
	"function_call.multiline.min_length": 120,
	"function_call.padding": false,
	"function_declaration.empty_padding": false,
	"function_declaration.group_to_block_spacing": "spaced",
	"function_declaration.multiline.comma_dangle": false,
	"function_declaration.multiline.element_count": 1,
	"function_declaration.multiline.leading_comma": false,
	"function_declaration.multiline.leading_comma.padding": true,
	"function_declaration.multiline.min_length": 1,
	"function_declaration.padding": false,
	"function_declaration.spacing_to_group": false,
	"indent_size": 4,
	"keywords.block_to_keyword_spacing": "spaced",
	"keywords.empty_group_spacing": false,
	"keywords.group_to_block_spacing": "spaced",
	"keywords.padding_inside_group": false,
	"keywords.spacing_to_block": "spaced",
	"keywords.spacing_to_group": true,
	"max_columns": 150,
	"metadata.multiline.element_count": 4,
	"metadata.multiline.min_length": 120,
	"method_call.chain.multiline": 3,
	"newline": "os",
	"parentheses.padding": false,
	"property.multiline.element_count": 4,
	"property.multiline.min_length": 120,
	"strings.attributes.quote": "double",
	"strings.convertNestedQuotes": false,
	"strings.quote": "double",
	"struct.empty_padding": false,
	"struct.multiline.comma_dangle": false,
	"struct.multiline.element_count": 4,
	"struct.multiline.leading_comma": false,
	"struct.multiline.leading_comma.padding": true,
	"struct.multiline.min_length": 120,
	"struct.padding": false,
	"struct.quote_keys": false,
	"struct.separator": " = ",
	"tab_indent": true,
	"tags.lowercase": true
  }

**Comment by jcberquist** [comment]
I can reproduce the issue with the `if` statements. The missing semicolons are tripping up the formatter. I should be able to improve that, but again, as I noted in the other issue, this sort of parsing/formatting is hampered by the fact that cfformat does not currently perform enough of a parse to easily recognize where statements end. 

I am going to need more information to try and reproduce the issues in the first comment. Could you possibly supply more context for them? As it stands, with the settings you supplied, and those sample statements on their own, I am not seeing the issues you describe.

**Comment by gls7** [comment]
Here is an example file that has been formatted 1, 2, and 3 times.

[formatting.zip](https://github.com/jcberquist/commandbox-cfformat/files/6031228/formatting.zip)

**Comment by gls7** [comment]
How's this going? We would love to use cfformat but this problem is a deal breaker. Let me know if there's more you need from me.

**Comment by jcberquist** [comment]
I have still not dealt with the `if` statements. There was an issue with `#`'s not inside strings which has been addressed. So this is not completely fixed, sorry.

**Comment by jcberquist** [comment]
Could you try v0.15.19 which I just published. At least with the sample file you sent, I think it performs better.

**Comment by gls7** [comment]
Will do. It's on my list but work has been rough lately.

**Comment by gls7** [comment]
Long time no see. It's been a busy summer. This works well for the tabbing. Just need to get the IF situation figured out.
