### ISSUE TITLE
Component attribute spacing around = character

### ISSUE THREAD

**Issue by bockensm** [jcberquist/commandbox-cfformat#111]
Consider the following code:

```
component extends = "base.component" output = false {
}
```

There do not appear to be any settings that would allow me to specify whether or not I want spaces around the equals characters. At the moment, the spaces are automatically removed regardless of my preferences.

**Comment by jcberquist** [comment]
At the moment, these are formatted as tag attributes. Are you looking for a global setting that affects spacing in tag attributes, or something that is specific to component attributes? I would prefer to add something general.

**Comment by bockensm** [comment]
I would be OK with one setting that hits component attributes as well as `property` and `param`.

**Comment by jcberquist** [comment]
I have added some new settings in `v0.17.0`: `metadata.key_value.padding`, `property.key_value.padding`, and `param.key_value.padding`. These are defaulted to `false`, but you can set them to `true` to get the padding you describe above. I did it this way with these settings to keep things in line with what was already present in the settings.
