### ISSUE TITLE
Incorrect indent after unwrapped text

### ISSUE THREAD

**Issue by hammond13** [jcberquist/commandbox-cfformat#112]
This works beautifully in most cases, but I found a problem with this simple case:

This:
```
<p>
    Testing
    <span>More code</span>
</p>
```

Formats to this:
```
<p>
    Testing
<span>More code</span>
</p>
```

Losing the indent after some unwrapped text.

**Comment by jcberquist** [comment]
Thanks for the report. I should hopefully be able to improve this.

**Comment by jcberquist** [comment]
I have hopefully improved the indent situation for code like the above. My focus in creating this formatter was on cfscript and so I don't expect the HTML printing to ever be perfect, but hopefully it will be passable.
