### ISSUE TITLE
"not found" error for cftokens_linux on Alpine

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#113]
When trying to use CFFormat in Pete Freitag's minibox container, which appears to be based on Alpine, the cftokens_linux binary throws the following error:

```
Cannot run program "/root/.CommandBox/cfml/modules/commandbox-cfformat/bin/v0.16.3/cftokens_linux": error=2, No such file or directory
```

The file is in fact there, but throws the same message even if you attempt to run the binary directly from bash:
```
docker run -it  foundeo/cfml-ci-tools sh
cd /root/.CommandBox/cfml/modules/commandbox-cfformat/bin/v0.16.3/
~/.CommandBox/cfml/modules/commandbox-cfformat/bin/v0.16.3 # ls -la
total 4208
drwxr-xr-x    2 root     root          4096 Jul 30 16:28 .
drwxr-xr-x    3 root     root          4096 Jul 30 16:28 ..
-rwxr-xr-x    1 root     root       4298624 Jul 30 16:28 cftokens_linux
~/.CommandBox/cfml/modules/commandbox-cfformat/bin/v0.16.3 # ./cftokens_linux
sh: ./cftokens_linux: not found
```
The issue appear to be related to a missing so library:
```
~/.CommandBox/cfml/modules/commandbox-cfformat/bin/v0.16.3 # ldd cftokens_linux
        /lib64/ld-linux-x86-64.so.2 (0x7fd643317000)
Error lolibpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fd643317000)needed by cftokens_linux)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fd643317000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fd643317000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by cftokens_linux)
Error relocating cftokens_linux: __memcpy_chk: symbol not found
Error relocating cftokens_linux: __vsnprintf_chk: symbol not found
Error relocating cftokens_linux: __snprintf_chk: symbol not found
Error relocating cftokens_linux: _Unwind_Resume: symbol not found
Error relocating cftokens_linux: _Unwind_GetRegionStart: symbol not found
Error relocating cftokens_linux: _Unwind_SetGR: symbol not found
Error relocating cftokens_linux: _Unwind_GetDataRelBase: symbol not found
Error relocating cftokens_linux: _Unwind_DeleteException: symbol not found
Error relocating cftokens_linux: _Unwind_GetLanguageSpecificData: symbol not found
Error relocating cftokens_linux: _Unwind_RaiseException: symbol not found
Error relocating cftokens_linux: _Unwind_GetIP: symbol not found
Error relocating cftokens_linux: _Unwind_Backtrace: symbol not found
Error relocating cftokens_linux: _Unwind_GetIPInfo: symbol not found
Error relocating cftokens_linux: _Unwind_GetTextRelBase: symbol not found
Error relocating cftokens_linux: _Unwind_SetIP: symbol not found
```
Is there any documentation on what C libs are required for the cftokens linux binary to run?

**Comment by michaelborn** [comment]
[subscribes to notifications...] :bell:

**Comment by jcberquist** [comment]
I believe the fundamental issue here is that the cftokens binary is compiled on Linux expecting glibc to be present. However, Alpine Linux uses MUSL libc instead. If you look at the Rust docs for platform support https://doc.rust-lang.org/rustc/platform-support.html you can see that Tier 1 "guaranteed to work" platforms require glibc on Linux. Now in Tier 2 "guaranteed to build" there is an option for targeting MUSL, so it is possible compiling with that target would allow the binary to run successfully. Another option is that one could try adding a glibc compatibility layer to the Alpine image: e.g. https://github.com/sgerrand/alpine-pkg-glibc.

**Comment by bdw429s** [comment]
Thanks for the info @jcberquist .  I installed the package you suggested above, but it simply gave me another error about a different library.  I spent the last 25 minutes or so Googling around the internet and installing all manner of packages into Alpine, each of which seemed to bump me farther down the line to another error, but none of them seeming to work.  Someone who understands more about this may need to try and crack it.  It's very easy to test this by just running `foundeo/cfml-ci-tools` like I showed above.

**Comment by jcberquist** [comment]
Alright, so thanks to @jfmontanaro we now have a cftokens build targeting MUSL, and if you install cfformat `v0.16.0` it should pull the correct binary and "just work" on Alpine Linux now. Could you please test and confirm this?

**Comment by bdw429s** [comment]
whoa, cool!  I'll test this tonight!

**Comment by bdw429s** [comment]
Just gave this a try and it seems to be working great! :+1:   Creating a MUSL build was probably far better than messing with all the Glibc dependencies.  Some of those packages were huge anyway.

**Comment by jcberquist** [comment]
Alright, I am really glad to hear this! This turns out to be a much easier solution than I thought it might have been, thanks to @jfmontanaro and his knowledge of building for Linux!

**Comment by michaelborn** [comment]
Wow, nice work folks!
