### ISSUE TITLE
Can't run test suite locally due to syntax issues in test files

### ISSUE THREAD

**Issue by sbleon** [jcberquist/commandbox-cfformat#118]
Hi, John. I'm trying to get set up for local development, but I haven't been able to run the test suite locally. After running `box start`, I get the following Lucee error:
![Screen Shot 2021-09-01 at 12 20 20 PM](https://user-images.githubusercontent.com/198711/131707548-ef4dbc3d-5325-48a8-b605-1a392ed72cff.png)

If I start with `cfengine=adobe@2021`, I get this error instead:
![Screen Shot 2021-09-01 at 12 20 31 PM](https://user-images.githubusercontent.com/198711/131707593-ec50ae0c-d156-44ee-ae9f-70753d52b5b7.png)

Here are the steps I took:
1. Clone this repo
2. Download `cftokens_osx` from https://github.com/jcberquist/cftokens/releases/tag/v0.16.6 and placing it at `bin/v0.16.6/cftokens`
3. Ran `box start` the repo's root directory.

Any idea what I'm doing wrong?

**Comment by jcberquist** [comment]
So definitely the server should be running Lucee - preferably the same version CommandBox is running. (Which should be no problem as that is the default server CommandBox will use when start is used without parameters.) Thanks for showing your stack trace, it looks like in the trace I see code coverage components from TestBox...I have never used this with code coverage support, and it looks like the error is coming from there - normally Lucee should never try to compile the test files. Can you run it with code coverage disabled?

**Comment by sbleon** [comment]
I'm not sure how or why coverage is enabled. I tried adding this to `/tests/index.cfm`:
`param name="url.coverageEnabled" default="false";`
but that didn't change anything. I'm pretty sure that coverage is disabled by default anyway.

I can see now that this codebase is incompatible with Adobe CF, but it doesn't matter because it will only run in the CommandBox env, which runs Lucee by default (or always?).

**Comment by sbleon** [comment]
That change had no effect because we're not using the testbox HTMLRunner, which automatically picks up on URL vars like the one I set.

Next, I tried this:
```
testbox = new testbox.system.Testbox({
    options: {
        coverage: {
            enabled: false
        }
    }
});
```
This also had no effect on the issue.

**Comment by sbleon** [comment]
Weird. The steps I posted above work fine on my other machine. It has an outdated CommandBox, so I'm updated that now to see what changes, if anything.

**Comment by sbleon** [comment]
Still works fine on this other machine with an updated CommandBox. I'll have to figure out what's wrong with my other machine.
