### ISSUE TITLE
Unable to parse error for functions returning a type that begins with '_'

### ISSUE THREAD

**Issue by doover** [jcberquist/commandbox-cfformat#119]
I created a component that is named starting with an underscore (to make it sort to the top of the directory).

If the init() function has a return type of the name of the component, cfformat reports "unable to parse" or "key [DELIMITED_ELEMENTS] doesn't exist".

For example:

file: _test_issue.cfc
```
component output="no" {
  _test_issue function init() {
    return this;
  }
}
```

When I do `cfformat run _test_issue.cfc` it tells me "Unable to parse" and a dump.

If I remove the returntype from the init then cfformat runs fine.

Error happens if any function returns a type with an underscore - I just noticed it first with an init for a file named _*

edit:
It seems to do "unable to parse" for shorter files. Not sure what causes the [DELIMETED_EMELEMENTS] error, but I saw it in a much longer file named _control.cfc and the error went away when I fixed the init() return.

**Comment by jcberquist** [comment]
This should be fixed in `v0.16.3`.
