### ISSUE TITLE
Remove Leading Comma Padding

### ISSUE THREAD

**Issue by richardherbert** [jcberquist/commandbox-cfformat#12]
It would be useful to have a settings that removed the space that is added after the comma moved by the `.leading_comma` settings. Maybe a setting like `.leading_comma.padding`

For example:

From this...

```
this.constraints = {
	'Title': { required: true, size: '1..255' },
	'Forename': { size: '0..255' },
	'Surname': { required: true, size: '1..255' }
}
```

...to this (`"struct.multiline.leading_comma":true`)...

```
this.constraints = {
	'Title': { required: true, size: '1..255' }
	, 'Forename': { size: '0..255' }
	, 'Surname': { required: true, size: '1..255' }
}
```

...finally to this (`"struct.multiline.leading_comma.padding":false`)...

```
this.constraints = {
	'Title': { required: true, size: '1..255' }
	,'Forename': { size: '0..255' }
	,'Surname': { required: true, size: '1..255' }
}
```

**Comment by jcberquist** [comment]
Thanks for creating the issue! I think I can add this pretty easily. One question: I notice in your examples above that you have the first element aligned with the leading commas; if you have tested the leading comma formatting you will have seen that it aligns the first element not with the leading comma, but rather with the elements that follow the commas. Which of these approaches matches your expectations?

**Comment by richardherbert** [comment]
I guess this is where it could get very subjective. 

Personally I find adding that extra space manually to the first line a bit "wrong" especially as VS-Code adds it to the second line after hitting return at the end of the first line which I then have to delete before starting the line with my comma. If `cfformat` is going to look after my formatting I could live with extra space prefix. 

So this would be fine...

```this.constraints = {
	 'Title': { required: true, size: '1..255' }
	,'Forename': { size: '0..255' }
	,'Surname': { required: true, size: '1..255' }
}```
