### ISSUE TITLE
[suggestion] Have <script> tags preserve indentation for improved readability

### ISSUE THREAD

**Issue by chris-singlebrook** [jcberquist/commandbox-cfformat#130]
I suggest that `<script>` tags should preserve indentation similar to how `// cfformat-ignore-start` does. The current behavior is to force everything within the '<script>' to the same indentation level. This makes javascript written within components harder to read.

Input: 
```html
<script>
  for(let i = 0; i < 4; i++){
    if(true){
      console.log("Hello World!");
    }
  }
</script>
```

Proposed output (no changes to indentarion):
```html
<script>
  for(let i = 0; i < 4; i++){
    if(true){
      console.log("Hello World!");
    }
  }
</script>
```

Current output:
```html
<script>
  for(let i = 0; i < 4; i++){
  if(true){
  console.log("Hello World!");
  }
  }
</script>
```

**Comment by jcberquist** [comment]
In version `v0.17.0` cfformat will attempt to preserve the existing indent in script tag bodies.
