### ISSUE TITLE
Tag type comments converted to script comments erroneously

### ISSUE THREAD

**Issue by gls7** [jcberquist/commandbox-cfformat#136]
Hey there, happy holidays!

We have some legacy cftag code that has comments within the tag attributes. See example below.

<cfset local.returnStruct.returnVal = {
	position = local.queuePosition,
	queueSize = local.server.throttle.getQueueSize(),
	timeoutMin = local.server.throttle.getQueuePositionPingTimeout(),
	
	messageText = local.application.keyExists("queueMessageText") ? local.application.queueMessageText : "",
	messageTextClass = local.application.keyExists("queueMessageClass") ? local.application.queueMessageClass : ""
} />

When we run the format, the comment gets converted to /* comment */ which breaks things. Can you determine that the comment is actually in the tag and leave it alone?

**Comment by jcberquist** [comment]
This should be fixed in `v0.17.2`. Thanks for the report!

**Comment by gls7** [comment]
Woot!
