### ISSUE TITLE
Latest version removing comments

### ISSUE THREAD

**Issue by lmajano** [jcberquist/commandbox-cfformat#139]
The latest version is also removing some comments:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/137111/149180740-b1def73f-29de-4b4e-be9e-0ce5e6bd1216.png">

**Comment by jcberquist** [comment]
What I have decided to do for now is ignore doc comments where not every line starts with an asterisk. This is in `v0.17.3`.
