### ISSUE TITLE
CommandBox no longer reloads on module installation

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#140]
CommandBox 5.4 stopped reloading the shell after installing a module (in favor of loading it on the fly) which means CFFormat doesn't work if a user tries to use it right away because cftokens.exe doesn't exist).  NOTE-- there is a bug in 5.4 which prevents newly installed modules from working right away that is fixed on the 5.5 alpha builds.  

CFFormat may want to do some sort of check before it runs that checks if the tokens exe is downloaded and download it right then since it can't be promised that the shell has been reloaded any longer.

**Comment by jcberquist** [comment]
Thanks for letting me know!

**Comment by jcberquist** [comment]
In rereading this it occurs to me that you are noting a problem specific to the 5.4 series?

**Comment by bdw429s** [comment]
> can you tell me how to reproduce the issue? I downloaded the CommandBox 5.5 alpha and tried a fresh install of CFFormat, and it went ahead and downloaded the binary even without the shell reload. Is there something I am missing?

I can still reproduce it on the latest 5.5 builds.  All I have to do is run
```bash
uninstall commandbox-cfformat
install commandbox-cfformat
cfformat check
```
The shell never reloads.  The tokens.exe binary is never downloaded, and this error is displayed:
```
× | Checking component formatting...
   | > Cannot run program "D:/.Command Box/cfml/modules/commandbox-cfformat/bin/v0.16.8/cftokens.exe": CreateProcess error=2, The system cannot find the file specified
   |-----------------------------------------------
```

Note, if you're using `package link` to "install" the module, that WILL still force a reload of the shell, which downloads the token.exe, so it's not a valid test.

**Comment by jcberquist** [comment]
Thanks @bdw429s! I can reproduce it if I uninstall cfformat and then try to reinstall in the same session. Interestingly, if I uninstall, exit commandbox, start commandbox up again, and then install cfformat, it does download the binary. I assume there is some lifecycle reason for this?

**Comment by bdw429s** [comment]
Well, I always assumed this was because you were listening to the `onCLIStart` interception point, which only fires when the CLI is started or restarted.  However, I just peeked at your code and I see you have the logic in your module's onLoad() method
https://github.com/jcberquist/commandbox-cfformat/blob/master/ModuleConfig.cfc#L13-L21
I actually would have expected that to work :thinking:   Let me double check that the modules are properly getting loaded when they are installed. This may turn out to be a bug in CommandBox not calling the `onLoad()`!

**Comment by bdw429s** [comment]
@jcberquist Ok, great news-- I figured out the issue.  While the latest CommandBox was properly registering and activating the module on installation, it was failing to UNREGISTER the module when you uninstalled it.  So even though the files were gone from disk, the module was still loaded in memory.  So when you uninstall and reinstall the module, it would work just fine, but the `onLoad()` was never called since the module skipped the activation the second time around since it was already activated.

The fix was to properly unload system modules when uninstalling them, which the ensures subsequent installs will fully re-load the module.  

I think you should be able to disregard this ticket.  I'll commit my fixes in a few minutes and you can help test.

**Comment by jcberquist** [comment]
Thanks for the update @bdw429s - I grabbed the latest build and it looks to me that this issue is fixed so I can close this ticket?
