### ISSUE TITLE
Improve --settings to have code samples

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#16]
Improve settings command (or add another command) that outputs a snippet of code to the console demonstrating the current configured settings.

**Comment by jcberquist** [comment]
I have added an argument (`settingInfo` for now) that you can supply with a setting name or prefix, and it will print information about that setting (or settings) to the console. This is in `v0.8.0`.
```bash
cfformat settingInfo=array
```
I have also linked to [reference.md](https://github.com/jcberquist/commandbox-cfformat/blob/master/reference.md) in the readme where the same information for all of the settings is also available. (You may have already seen this.)

If you want to see what the currently configured settings do you can run `cfformat` on a single file and it will print the formatted file to the console.

**Comment by bdw429s** [comment]
@jcberquist The reference file is excellent!

So far as a sample, I understand I could just run the command on a file of my own, but I still see value in coming up with some basic 10-15 lines of script code that covers the majority of settings that can be used as a baseline to get a good idea of how your current settings will operate.  It's just nice to have an out-of-the box example right there.

For example if you look in CF Builder preferences, here is the sample bit of code that shows you how the "Java" > "Code Style" > "Formatter" settings will look:

```java
**/**
* A sample source file for the code formatter preview
*/

package mypackage;

import java.util.LinkedList;

public class MyIntStack {
	private final LinkedList fStack;

	public MyIntStack() {
		fStack = new LinkedList();
	}

	public int pop() {
		return ((Integer) fStack.removeFirst()).intValue();
	}

	public void push(int elem) {
		fStack.addFirst(new Integer(elem));
	}

	public boolean isEmpty() {
		return fStack.isEmpty();
	}
}
```

And here's the sample code that you are shown to see how the "ColdFusion" > "Profiles" > "Editor" > "Formatter" settings will look.

```cfml
<cftry>
	<cfset print(10)>
	<cfset a = 10>
	<cfoutput>#a#</cfoutput>
	
	<cfscript>
		
		function print(int count) {
			for(i = 1; i < count; i++) {
				writeOutput(i);
			}
		}
		
	</cfscript>
	
<cfcatch type="Any">
</cfcatch>
</cftry>
```

There is also a sample XML file under "Ant" > "Editor" > "Formatter".

**Comment by bdw429s** [comment]
Oh also on a side note, you may want to think about breaking out the `cfformat` command to be a namespace with multiple commands in it.  It seems like we're starting to overload cfformat with quite a few things at this point.  Since `cfformat` isn't a binary, there's no need to try and route every command through it, otherwise you'll end up with a lot of optional params or making it so generic you'll have an action param or something which duplicates the idea of just using the namespace.

**Comment by jcberquist** [comment]
Ok, I can try to come up with some basic example code to format as an illustration 😄

Regarding moving to a namespace, that is something I have been considering. I agree the command is getting overloaded. I haven't done it yet because I really wanted `cfformat {my.cfc}` to work.

**Comment by bdw429s** [comment]
You know I've had this ticket in forever, but I never did it because I never hit a case where I couldn't solve it by just using namespaces:

https://ortussolutions.atlassian.net/browse/COMMANDBOX-120

**Comment by bdw429s** [comment]
Another option even though it's a little messy would be to create additional commands in the root namespace like
```bash
cfformat-settings
cfformat-example
```
etc
It would allow you to keep `cfformat` as a top level command, but it isn't quite idiomatic for CommandBox's command organization.
