### ISSUE TITLE
Wizard to create settings file

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#19]
This is just a random idea, but how about a command that presents the user with a little wizard to choose each setting with a code sample of each one.  I'm imagining clearing the screen after each question and outputting two (or however many options there are) code samples demonstrating what the setting does, and then use the multi-select input for the user to toggle between the settings to choose what they want.  Default each question to the default value.  When the user is finished, we spit out a JSON file based on their responses and show them an example of their final choice.

**Comment by elpete** [comment]
Oooh...this would be nice.  I wonder if we can change `reference.md` to be `reference.json` and include all the options programatically?

@jcberquist, if this sounds interesting to you, I can check out this one.

**Comment by elpete** [comment]
Something like this:

**Comment by jcberquist** [comment]
Hey @elpete, feel free to check it out 😀. I actually currently generate the `reference.md` file with the task runner (`build.cfc`) in the root of the repository, pulling data from [data/reference.json](https://github.com/jcberquist/commandbox-cfformat/blob/master/data/reference.json) and generating examples from that file that are stored in [data/examples.json](https://github.com/jcberquist/commandbox-cfformat/blob/master/data/examples.json).

**Comment by elpete** [comment]
Perfect!

**Comment by elpete** [comment]
I'm getting close on this one.  I have two questions:

1. The command name.  I personally would be using nested command namespaces.  Something like
```
cfformat run
cfformat settings list
cfformat settings wizard
```
I understand this isn't how this project is set up.  I guess I'm asking what you would like the command to be instead.

2. Some of the examples in the `examples.json` have an empty string key `""`.  This makes it a little awkward to show in the wizard as they are usually choosing between `true` and `false` or other values like that.  Are you opposed to giving it a proper name?

**Comment by elpete** [comment]
Here's a demo of the wizard in it's current state: https://www.dropbox.com/s/3mukp3yu4ou4x4v/cfformat%20demo.mp4?dl=0

**Comment by mjclemente** [comment]
Just chiming in to say awesome work on this project. To both of you. 💯 

Many thanks @jcberquist and @elpete

**Comment by jcberquist** [comment]
I have finally merged a settings wizard into master thanks to @elpete!

**Comment by bdw429s** [comment]
Hot dog, that demo above is exactly what I was thinking!
