### ISSUE TITLE
Watcher not working 

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#20]
```bash
cfformat ./ --watch
```
Gives me this error on save:

```
```Error invoking external process
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src\libcore\result.rs:999:5note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
D:\.Command Box\cfml\modules\commandbox-cfformat\models\CFFormat.cfc: line 140
138:     function tokenizeFile(fullFilePath) {
139:         var tokens = '';
140:         cfexecute(name=executable arguments="""#fullFilePath#""" variable="tokens" timeout=10);
141:         if (!isJSON(tokens)) {
142:             throw(tokens);```
```

Looks like we're double appending the base path on this line:
```js
var allFiles = files.added.append(files.changed, true).map((p) => fullPath & p);
```
Removing the map made it work for me.

**Comment by jcberquist** [comment]
I tested this on OSX and the paths returned by the watcher are relative (to the watched directory). I think they are supposed to be that way but are actually not on Windows - I looked at `Watcher.cfc` and this line [Watcher.cfc#L231](https://github.com/Ortus-Solutions/commandbox/blob/development/src/cfml/system/util/Watcher.cfc#L231) uses a hard-coded `/` between the directory and file name, which means the replace will work on OSX but not on Windows.

**Comment by bdw429s** [comment]
Interesting, can you send a pull to fix the watcher?
