### ISSUE TITLE
Option to not format comments.

### ISSUE THREAD

**Issue by renkejr-pkwy** [jcberquist/commandbox-cfformat#29]
The formatter currently strips all leading and trailing white space and then indents.

```
/**
 * Description
 *
 * @param Some parameter info
 */
```

is now

```
/**
* Description
*
* @param Some parameter info
*/
```

Unfortunately, this breaks my doc-block extension since it is expecting an extra space after the indent.

**Comment by jcberquist** [comment]
Thanks for raising the issue. If and how to format comments is something I have been unsure about. So it is helpful to see this issue - may I ask what doc-block extension you use? I wonder if I should just switch doc comments to be formatted the way you have, make it an option, or just leave them untouched.

**Comment by renkejr-pkwy** [comment]
The extension is Document This.  I tried a couple of other extension as well.  The extensions all work until the document gets reformatted.  I then have to add the extra leading space or delete the comment if I want make any changes.

Not a big deal but, in general, I'd prefer comments don't get reformatted anyway.

**Comment by jcberquist** [comment]
I have been working on this. I took a look at what prettier does with JS files and it looks to me like it renders block comments as is, unless every line starts with a `*`, in which case it aligns the lines on the `*`'s. So my current plan is to create a new settings for this sort of alignment: https://github.com/jcberquist/commandbox-cfformat/blob/master/reference.md#commentasterisks

By default it will copy prettier and align all lines on the `*`, but you can disable this if you want. Absent the leading asterisks, comments should be renderered as is without being reformatted.

**Comment by jcberquist** [comment]
This is now out in `v0.10.0`. Note: in order to convince CommandBox to update to that version you will either need to uninstall and then reinstall - or explicitly install that version. @bdw429s pointed out to me that with semver minor version bumps with a major version of `0` are treated as major version updates and so are not automatic upgrades.
