### ISSUE TITLE
Add a `watch` command

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#3]
The `watch` command would watch all `.cfc` files for changes and format each added or changed file.

The biggest question here would be if you nested the original command (like `cfformat run`) to allow for `cfformat watch` or if you used a different command name (like `cfformat-watch`).

(Again, happy to implement this.)

**Comment by jcberquist** [comment]
This is a really neat idea! Could this be done with by adding a `--watch` flag on the original command, or would that lead to trouble? I haven't used the CommandBox `watch` plumbing before now, so I am not very familiar with it. If that won't work, I think I would prefer adding a `cfformat-watch` command over nesting the commands in a namespace.

**Comment by elpete** [comment]
I think I can do the `--watch` flag.  Look for a PR.
