### ISSUE TITLE
method chaining formatting

### ISSUE THREAD

**Issue by scottsteinbeck** [jcberquist/commandbox-cfformat#30]
It would be awesome to have chained methods be indented on a new line. ex.
``` 
bookService
   .getVersions( bookDirectory )
   .each( ( v ) => print.line( v ) );
```
as opposed to
```bookService.getVersions( bookDirectory ).each( (v) => print.line( v ) );``` 
or maybe have a max length

**Comment by jcberquist** [comment]
This is currently hard coded to print on one line if there are less than three method calls in the chain (and if it fits in the specified line column limit and there are no newlines in the output from other sources). At three or more method calls in the chain, it will always print each call on a new line. I was trying to copy what `prettier` does - but I am open to this being more flexible.

**Comment by scottsteinbeck** [comment]
Oh, I didn't realize that it worked that way. For my use case, I think it works the way it is. If you did want to add a max method length, that would be awesome!

**Comment by jcberquist** [comment]
@scottsteinbeck Sorry for the delay in getting back to you. When you say "max method length", what are you thinking of there? Do you mean max length on a single line? Or max method count in the chain?

**Comment by scottsteinbeck** [comment]
max method count in the chain.

Scott Steinbeck
scottsteinbeck@gmail.com
661-717-6486

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/03/19,
09:51:27 PM

**Comment by scottsteinbeck** [comment]
Your awesome @jcberquist! Thank You!

**Comment by jcberquist** [comment]
I added a settings `"method_call.chain.multiline": 3` (default) - the number determines at what method chain length the method calls will always be broken on to multiple lines.
