### ISSUE TITLE
Spaces mistakenly removed

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#34]
The following code causes cfformat to return invalid syntax:

Input:
include "foo.cfm";

Returns:
include"foo.cfm";

Workaround:
include template="foo.cfm";

**Comment by jcberquist** [comment]
I can't reproduce this one. I know it was an issue earlier, but I thought I had fixed it. (I even have a [test case](https://github.com/jcberquist/commandbox-cfformat/blob/master/tests/specs/keywordsSpec.cfc#L17-L19) for it.) What OS are you running that on?

**Comment by chapmandu** [comment]
Hmm.. Let me confirm I have the latest version of cfformat. I'm using Ubuntu.

**Comment by jcberquist** [comment]
@chapmandu Any update on this one?

**Comment by chapmandu** [comment]
This was resolved after updating. Thanks!
