### ISSUE TITLE
Parser doesn't handle nested tag comments

### ISSUE THREAD

**Issue by mbandizzle** [jcberquist/commandbox-cfformat#4]
This line of code throws an error that 1 doesn't exist on tag-based code where a comment is inside of another comment.

https://github.com/jcberquist/commandbox-cfformat/blob/master/models/cftags/TagComments.cfc#L20

like so

```html
<!--- test

  <!--- moar comments
  --->

--->
```

The array on the line above expects to find only nested arrays, but instead, nested structs are present which cannot be indexed as `t[1]`.

**Comment by jcberquist** [comment]
Thanks for the report. I have added enough of a fix that the formatter will not crash anymore.
