### ISSUE TITLE
Can't format files named $$foo.cfc

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#41]
`cfformat dir/$$foo.cfc`

Returns "dir/22004foo.cfc is not a valid file or directory."

**Comment by jcberquist** [comment]
I can't reproduce this myself. It looks to me that by the time the cfformat command sees your path it has `22004` instead of `$$`. How is the `$$` entered and encoded? If it is actually two `$` then this should work fine, but maybe there is some sort of encoding issue?

**Comment by chapmandu** [comment]
Interesting that you cannot reproduce it. You may be onto something regarding encoding as it will format if the directory is being watched.

When I saw this issue I right clicked my vscode tab and copied the relative path then pasted into my bash terminal (Ubuntu). I'll check if there is some kind of encoding the value in the clipboard.

**Comment by chapmandu** [comment]
OK.. bash tries to evaluate the $ as a variable. Escaping the $ works, which would explain why these files are processed using `watch`

`cfformat dir/\$\$foo.cfc`

Looks like I may re-think my file name convention :)
