### ISSUE TITLE
Comma formatting results in invalid syntax

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#46]
This may be an edge case and tricky to solve, but changing leading to trailing commas with a commented line of code results in a syntax exception. Note missing comma after `local.from`,

input:
```
send(
  to = local.to
  ,from = local.from
  // ,user=local.user
  // ,thing=local.thing
  ,body = local.body
);
```

result:
```
send(
  to = local.to,
  from = local.from
  // ,user=local.user, // ,thing=local.thing
  body = local.body
);
```

expected:
```
send(
  to = local.to,
  from = local.from,
  // ,user=local.user, // ,thing=local.thing
  body = local.body
);
```

**Comment by jcberquist** [comment]
Thanks for the report, this is getting tricky :) Even prettier will start inlining multiple comments at a certain point, but it doesn't eat any code. I have a potential fix in place that I will push, and it passes the tests, but I am not confident that there isn't another scenario out there that will break things still.
