### ISSUE TITLE
Eaten code with extraneous hashes

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#49]
Input:
```
loop from=1 to=#params.quantity# index="local.i" {
}
```

Expected:
```
loop from=1 to=#params.quantity# index="local.i" {
}
```

Actual:
```
loop from=1 to=# params {
}
```

Admittedly, the input syntax is pretty smelly.. but a fair chunk of code was eaten.

**Comment by jcberquist** [comment]
Thanks for the report, this is an error with the underlying syntax scopes, it doesn't recognize `to=#params.quantity#` correctly. I will have to see what can be done about that.

**Comment by jcberquist** [comment]
v0.12.15 was just published, and it has an updated binary which should correctly parse the above syntax.
