### ISSUE TITLE
Space between `!`

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#52]
Small thing, but I like to have space between a bang (`!`) and the code it is negating.

```cfc
component {

    function run() {
        if ( ! true ) {
            writeDump( "Hi!" );
        }
    }

}
```

Currently this squashes into `if ( !true ) {`.

Additionally, if I use a double bang (`!!`) I would keep the bangs together: `if ( !! true ) {`.

**Comment by jcberquist** [comment]
There are a number of other prefix operators (e.g. `++`, `--`, `+`, `-`), is the `!` the only one where you want this? In any case, in order to support this a new setting will be needed. What do you suggest?

**Comment by elpete** [comment]
I can also be convinced that this isn't worth it and get used to the formatting.  I just find that I lose the bang (`!`).

It's probably not worth a new setting, especially because I wouldn't want the same treatment to other prefix or postfix operators.  Let's close this one.  Thanks.
