### ISSUE TITLE
Add support for safe navigation operator

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#57]
It looks like the safe navigation operator (`?.`) is being interpreted as a ternary operator.  This causes some code breakage.

Config: default

Source:
```cfc
component {

    function functionCallWithSafeNavigationOperator() {
        return getFoo()?.getBar();
    }

    function structWithSafeNavigationOperator() {
        return variables?.foo?.bar;
    }

}
```

Current Output:
```cfc
component {

    function functionCallWithSafeNavigationOperator() {
        return getFoo() ? .getBar();
    }

    function structWithSafeNavigationOperator() {
        return variables ? .foo ? .bar;
    }

}
```

**Comment by elpete** [comment]
Actually, it looks like Lucee still parses this correctly.  I'm surprised.  However, I don't think that's the aesthetic we want since it _looks like_ a ternary this way.

**Comment by jcberquist** [comment]
Thanks! I didn't have any syntax highlighting support for the safe navigation operator in place.
