### ISSUE TITLE
Chinese characters are garbled

### ISSUE THREAD

**Issue by vience** [jcberquist/commandbox-cfformat#58]
CFFormat CFC/CFM files contains Chinese will unreadable, even saved with UTF-8 encoding.

```cfscript
  public void function index( event, rc, prc ) {

    // 中文测试
    // This is a Chinese text
  }
```

will be output as

```cfscript
public void function index( event, rc, prc ) {
    // 涓枃娴嬭瘯
    // This is a Chinese text
  }
```

After reading source code, I found cftokens.exe (v0.13.6)  cause Chinese characters to be displayed garbled. 

Can anyone help me fixing the problem? 
Thanks

**Comment by vience** [comment]
I found using **outputFile** instead of **variable** will produce correct result.

···cfscript
cfexecute(name=executable, arguments="""#fullFilePath#""", timeout=10, outputFile="#temp#");
```

The **variable="tokens"** of CFExecute will messed up the source code.

**Comment by jcberquist** [comment]
Yes, you have identified where the issue occurs. On a Windows machine, when cfexecute captures output to a variable, I believe it uses the default encoding of `cp1252` and not `utf-8`. This is only an issue on Windows. Could you try creating a `commandbox.properties` file next to the `box.exe` binary and put the following in it:
```
file.encoding=utf-8
```
The next time CommandBox is started up, it should pick that java property up, and start using `utf-8` for cfexecute output.

**Comment by vience** [comment]
You're genius !!! 
Yes, a commandbox.properties file contains ``` file.encoding=utf-8 ``` solved the problem.
 
Also, I've comfirmed this is only an issue with **CFEXECUTE** on Windows system. I've tested cfformat with Ubuntu Linux, it's really great!
