### ISSUE TITLE
`static` is not supported

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#60]
This component fails to be parsed.

```cfc
component {

    static {
        foo = "bar";
    }

}
```

https://docs.lucee.org/guides/lucee-5/component-static.html

**Comment by jcberquist** [comment]
This should be fixed in `v0.13.8`, the scopes assigned to the block start and end turned out to be unbalanced which threw everything off - I updated the underlying syntax to take care of this.
