### ISSUE TITLE
Show a diff when check fails

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#63]
Maybe only with a `--verbose` flag?

**Comment by jcberquist** [comment]
Interesting idea - are you thinking of using this in a CI environment when checking many files, or locally, or both?

**Comment by elpete** [comment]
Mostly for CI. As we’ve been pushing and adopting for cfformat more, some times we wish we had a better idea what was needing changes.

**Comment by jcberquist** [comment]
Well, that was fun to do 😀  - there is now a `--verbose` flag for `cfformat check` in `v0.13.9` - please try it out and let me know if it is what you were looking for.

**Comment by elpete** [comment]
Works like a charm.  Thanks!
