### ISSUE TITLE
function_declaration.padding doesn't work on some functions

### ISSUE THREAD

**Issue by bockensm** [jcberquist/commandbox-cfformat#68]
In this block of code:
```
component {

    function doSomething(arg1) {
        return {
            diConfig: {
                loadListener: function(di1) {
                    di1.declare( "QueryBuilder" ).asValue( getBeanFactory( "qb" ).getBean( "QueryBuilder" ) );
                    di1.declare( "SchemaBuilder" ).asValue( getBeanFactory( "qb" ).getBean( "SchemaBuilder" ) );
                    di1.declare( "Logger" ).asValue( getBeanFactory( "logbox" ).getBean( "LogBox" ) );
                }
            }
        }
    }

}

```

I'd expect the"di1" parameter of the `loadListener` function to be padded with spaces, but it doesn't happen when "function_declaration.padding" is set to true. "arg1" for the `doSomething` function does get padded.

**Comment by jcberquist** [comment]
So, for better or worse, the settings for anonymous function declarations have been split off from the settings for named function declarations. The setting that affects that padding is `"function_anonymous.padding"`.

**Comment by bockensm** [comment]
Thanks!
