### ISSUE TITLE
Ternary operator colon gets replaced with equals

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#73]
Input:
`str = {"name" = 1 == 1 ? 1 MOD 1 : 0};`

Output:
`str = {"name" = 1 == 1 ? 1 MOD 1 = 0};`

Seems to be when a ternary is inside a struct definition.

**Comment by jcberquist** [comment]
It appears the underlying issue here is that the `mod` operator was not being identified by the syntax. This is fixed in `v0.14.4`.
