### ISSUE TITLE
Lucee "tag island" syntax doesn't work

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#74]
CFFormat doesn't work right when you have a tag island in the middle of script code which is bookended by three back ticks.

```
component extends="BaseTask" {
	
	function run() {
		query name="local.qry" {
			```
				DROP TABLE 	TABLE_NAME
				SELECT 		foo, bar, baz
				INTO 		TABLE_NAME
				FROM
				(
					SELECT 		foo, bar, baz
					FROM 		foo
						INNER JOIN foo
						INNER JOIN foo
						INNER JOIN foo
						INNER JOIN foo
					WHERE 		(foo.Status IN ( 1,3,4,5,6,7,8,9 ))
				) UN
			
				SELECT @@rowcount as _count
				
				CREATE NONCLUSTERED INDEX foo ON TABLE_NAME (foo);
				CREATE NONCLUSTERED INDEX foo ON TABLE_NAME (foo);
				CREATE NONCLUSTERED INDEX foo ON TABLE_NAME (foo);
				
				
			```
		}
		print.greenLine( '#qry._count# records updated in TABLE_NAME!' ).toConsole();
	}
	
}
```

The code inside the tag island is just truncated.

**Comment by bdw429s** [comment]
Post formatting, the file looks like this
```
component extends="BaseTask" {

        function run() {
                query name="local.qry" {
                        ```
                                DROPTABLE TABLE_NAME SELECT foo;
                        CREATE NONCLUSTERED INDEX foo ONTABLE_NAME( foo );
                        CREATE NONCLUSTERED INDEX foo ONTABLE_NAME( foo );


                                                ```
                }
                print.greenLine( '#qry._count# records updated in TABLE_NAME!' ).toConsole();
        }

}
```

**Comment by jcberquist** [comment]
Given how I feel about this syntax, I am inclined to mark this "works as designed" 😛 

But seriously, I obviously don't want it to delete code. I am going to have to consider how to handle this. I haven't actually supported highlighting tag islands properly in the underlying syntax yet, so it will depend on getting that in place first.

**Comment by bdw429s** [comment]
Heh, you know I'm not much of a fan of the tag islands either, but I'm converting a bunch of old .cfm scheduled tasks for a client to new script-based CommandBox Task Runners and most of their scheduled tasks have a lot of large and hairy SQL code in them.  It's really really nice and the most readable solution I've found to just be able to slam the contents of the cfquery tag into a tag island and convert everything around it to script.  Then I'm not having to wrap all the SQL strings in quotes and escape stuff.  The highlighting in my IDE is more natural and nested tags like cfqueryparam "just work" without me needing to touch the SQL blocks and risk screwing them up.   I don't know if it's on purpose or on accident, but the VS Code CFML plugin handles this beautifully too and I get all my SQL nicely highlighted right there inside the tag island.  

For my purposes, I wouldn't even care if you just left the contents of the tag island alone so long as it didn't truncate the text.

**Comment by bdw429s** [comment]
oops, accidentally hit "close and comment" :)

**Comment by jcberquist** [comment]
`v0.15.0` is out and it recognized the tag island - you might find your indents messed with a bit, but it will not eat code anymore.

**Comment by bdw429s** [comment]
Awesome, thanks @jcberquist !
