### ISSUE TITLE
Add a preCommit command

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#8]
Add a command for use with commandbox-githooks that will do the following: https://prettier.io/docs/en/precommit.html#option-5-bash-script

**Comment by elpete** [comment]
@jcberquist I'd like to add this as a first class command.  The idea would be to use it with [`commandbox-githooks`](https://github.com/elpete/commandbox-githooks).

```json
{
  "githooks": {
    "preCommit": "cfformat format-staged",
    "postCommit": "cfformat format-staged-cleanup"
  }
}
```

This would:
1. Get the staged files from git
2. Format each of them
3. Add the changes to the index.
4. Cleanup the index postCommit

How do you feel about this?

**Comment by elpete** [comment]
Here's an example as a recipe:
```
set FILES=`echo "git diff --cached --name-only" | run | grep .cfc`
echo ${FILES} | forEach "cfformat \${item} --overwrite
set LINEBREAK=`#chr 10`
set FILELIST=`#listChangeDelims ${FILES} " " ${LINEBREAK}`
echo "git add ${FILELIST}" | run
exit 0
```

**Comment by jcberquist** [comment]
I am not familiar with `commandbox-githooks` so forgive me: What is the relationship between the preCommit `cfformat format-staged` and the recipe you provided above?

**Comment by elpete** [comment]
The idea is similar to `husky` in Node land — run commands on certain git events.  The recipe is a way to accomplish the steps listed above.  The command I'm suggesting would make it so we don't need to distribute the recipe some other way.

**Comment by jcberquist** [comment]
Ok, well that sounds fine to me. 

I need to add a way to tokenize a set of files without making a full pass through a directory. The binary is very fast, but it takes ~50ms to start up and load the syntax files into memory. If I can get it to tokenize a set of files without restarting it each time the cumulative time savings adds up.

**Comment by jcberquist** [comment]
This should be doable now, since `cfformat` can now work on an arbitrary list of files. How are you envisioning `cfformat format-staged` working - is that supposed to be a "magic" string that is not treated as a path? Or would it be better to to `cfformat --format-staged`?

**Comment by elpete** [comment]
I'm currently looking into solving this just in a package script, so cfformat would not need any special features to accommodate this.
