### ISSUE TITLE
Mac < 10.15 issues with cftoken

### ISSUE THREAD

**Issue by lmajano** [jcberquist/commandbox-cfformat#86]
```
Error invoking external process
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwinReferenced from: /Users/ortus/Sites/projects/commandbox/src/cfml/modules/commandbox-cfformat/bin/v0.16.0/cftokens_osx (which was built for Mac OS X 10.15)Expected in: /usr/lib/libSystem.B.dylibdyld: Symbol not found: ____chkstk_darwinReferenced from: /Users/ortus/Sites/projects/commandbox/src/cfml/modules/commandbox-cfformat/bin/v0.16.0/cftokens_osx (which was built for Mac OS X 10.15)Expected in: /usr/lib/libSystem.B.dylib
```

I have my test mac running with High Sierra (10.13.6) but it can't run cfformat as it seems the cftokens has been compiled for use on 10.15+.  Is there a way we can get a build to support older macs?

**Comment by jcberquist** [comment]
@lmajano I don't have access to 10.13 so I am not going to be able to test this right now, but I tried recompiling cftokens with 10.13 specified as the minimum version.

Could you try replacing the `cftokens_osx` binary you have on your system (location specified in the error message) with the binary I have attached here?

[cftokens_osx.zip](https://github.com/jcberquist/commandbox-cfformat/files/5196998/cftokens_osx.zip)

**Comment by lmajano** [comment]
I can verify that it works @jcberquist !! Now my old mac can format ❤️
