### ISSUE TITLE
require or disallow trailing commas

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#91]
It would be amazing to have some configuration for fixing/removing dangling trailing commas. 
To either enforce, remove or at least prevent a newline if they are being used.

input
```
foo = {
    bar: "baz",
    qux: "quux",
};
baz = [
  1,
  2,
];
```

actual
```
foo = {
    bar: "baz",
    qux: "quux",

};
baz = [
  1,
  2,

];
```

wanted
```
foo = {
    bar: "baz",
    qux: "quux",
};
baz = [
  1,
  2,
];
```

Eg: https://eslint.org/docs/rules/comma-dangle

**Comment by jcberquist** [comment]
Yeah, the extra line is not desirable, and at least I should be able fix that. I am not sure about enforcing (or removing) a trailing comma with a rule, but maybe that would be a good idea, if possible.

**Comment by jcberquist** [comment]
`v0.15.11` is out, which adds settings such as `array.multiline.comma_dangle` that can be set to true or false to control this behavior.
