### ISSUE TITLE
concats the "IN" if upper case in a for loop definition

### ISSUE THREAD

**Issue by bshea5** [jcberquist/commandbox-cfformat#92]
A definition for a for loop using "IN" in all caps is converted into bad syntax, by concatenating the "IN" the following value. Example below:

for (var ieeetype IN Dictionary().ieeetypes) --> for (var ieeetype INDictionary().ieeetypes)

**Comment by jcberquist** [comment]
Thank you for the report. `v0.15.12` is out now, and should fix this.
