### ISSUE TITLE
Formatting a file with Unicode chars on Windows corrupts text

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#94]
It would appear that CFFormat isn't using UTF-8 when reading/writing files.  

I have a file with the following text
```js
// TODO: Cast page as int because ¯\_(ツ)_/¯
```
and formatting the file on my Windows machine changes the text to this:
```js
// TODO: Cast page as int because Â¯\_(ãƒ„)_/Â¯
```

**Comment by jcberquist** [comment]
Thanks @bdw429s, it looks like I still have a utf-8 issue when formatting sets of files. Incidentally, I noticed with that text that when running `cat file.txt` from CommandBox it also garbles the output to the terminal.

**Comment by bdw429s** [comment]
I can `cat` files without issues.  I wonder if it's your terminal

![image](https://user-images.githubusercontent.com/584009/102263302-bb87da00-3ed9-11eb-875b-aa8780edadac.png)

That said, I'll still add `, 'utf-8'` to the `fileRead()` in the `cat` command.

**Comment by jcberquist** [comment]
I was afraid of that 😀  - I will have to look into what is up with my terminal.
