### ISSUE TITLE
"Watch" ignores .cfformat.json 

### ISSUE THREAD

**Issue by Daemach** [jcberquist/commandbox-cfformat#96]
It appears that "cfformat watch" ignores the .cfformat.json file, while "cfformat run" does not.  The lack of consistency caused me a few hours of trying to figure out what was failing.  IMHO, if a .cfformat.json file exists, it should be used by default by all cfformat operations unless overridden by passing it a different settings file name.

**Comment by jcberquist** [comment]
Can you confirm for me you are using the latest version of cfformat? This issue has been raised before: #65  - in my testing locally it works correctly with the current version.

**Comment by Daemach** [comment]
I can confirm it was happening with  v0.15.12 but I see you have a new version up today.  I'll have to test that.

**Comment by CreativeNotice** [comment]
Can confirm this is what I'm seeing as well. Just installed cfformat from forgebox this morning.
Running `cfformat watch settingsPath=.cfformat.json` does utilize the settings file.
