### ISSUE TITLE
Qb statements getting split

### ISSUE THREAD

**Issue by Daemach** [jcberquist/commandbox-cfformat#98]
I really love this tool.  Can you tell me what setting would keep the querybuilder statements (in red) from getting split?  I know they work as is, but the red is glaring :)  I would prefer to see the following if possible: https://www.screencast.com/t/FXsPSODj

![image](https://user-images.githubusercontent.com/12553953/103904624-5bd4b700-50b2-11eb-9f1b-a18b36a0188d.png)

**Comment by elpete** [comment]
It's because `query` is a tag-in-script word. CFFormat splits the chain on
to separate lines and then the parser wonders if you were using the
tag-in-script `query`. Using a different variable name like `qb` instead of
`query` fixes the red.

**Comment by jcberquist** [comment]
@Daemach: what @elpete said :) - this is a limitation of the syntax highlighting in VS Code. VS Code (and others) typically do their highlighting line by line - so `query` on a line by itself is ambiguous - it could be a variable, or it could be the start of a tag in script. The syntax highlighting chooses a tag in script in such situations - so for now, the thing to do is what @elpete  said and use a different variable name.
